version: '3.3'

services:

  tubecast:
    build:
      context: ./
    image: tubecast
    restart: "no"
    ports:
      - 8000:8000
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    entrypoint: nodemon run.js
    environment:
      NODE_PATH: "./lib"
      NODE_ENV: "development"
